function [alifMad] = alifMad4Train(rw,cl)

%GET ALPHABETS
%==============

alifMad1 =imread('alifMad1.bmp');
alifMad2=imread('alifMad2.bmp');
alifMad3 =imread('alifMad3.bmp');
alifMad4 =imread('alifMad4.bmp');
alifMad5 =imread('alifMad5.bmp');
alifMad6 =imread('alifMad6.bmp');
alifMad7 =imread('alifMad7.bmp');
alifMad8 =imread('alifMad8.bmp');
alifMad9 =imread('alifMad9.bmp');
alifMad10 =imread('alifMad10.bmp');
alifMad11 =imread('alifMad11.bmp');
alifMad12=imread('alifMad12.bmp');
alifMad13 =imread('alifMad13.bmp');
alifMad14 =imread('alifMad14.bmp');
alifMad15 =imread('alifMad15.bmp');
alifMad16 =imread('alifMad16.bmp');
alifMad17 =imread('alifMad17.bmp');
alifMad18 =imread('alifMad18.bmp');
alifMad19 =imread('alifMad19.bmp');
alifMad20 =imread('alifMad20.bmp');
alifMad21 =imread('alifMad21.bmp');
alifMad22=imread('alifMad22.bmp');
alifMad23 =imread('alifMad23.bmp');
alifMad24 =imread('alifMad24.bmp');
alifMad25 =imread('alifMad25.bmp');
alifMad26 =imread('alifMad26.bmp');
alifMad27 =imread('alifMad27.bmp');
alifMad28 =imread('alifMad28.bmp');
alifMad29 =imread('alifMad29.bmp');
alifMad30 =imread('alifMad30.bmp');
alifMad31 =imread('alifMad31.bmp');
alifMad32=imread('alifMad32.bmp');
alifMad33 =imread('alifMad33.bmp');
alifMad34 =imread('alifMad34.bmp');
alifMad35 =imread('alifMad35.bmp');
alifMad36 =imread('alifMad36.bmp');
alifMad37 =imread('alifMad37.bmp');
alifMad38 =imread('alifMad38.bmp');
alifMad39 =imread('alifMad39.bmp');
alifMad40 =imread('alifMad40.bmp');
alifMad41 =imread('alifMad41.bmp');
alifMad42=imread('alifMad42.bmp');
alifMad43 =imread('alifMad43.bmp');
alifMad44 =imread('alifMad44.bmp');
alifMad45 =imread('alifMad45.bmp');
alifMad46 =imread('alifMad46.bmp');
alifMad47 =imread('alifMad47.bmp');
alifMad48 =imread('alifMad48.bmp');
alifMad49 =imread('alifMad49.bmp');
alifMad50 =imread('alifMad50.bmp');
alifMad51 =imread('alifMad51.bmp');
alifMad52=imread('alifMad52.bmp');
alifMad53 =imread('alifMad53.bmp');
alifMad54 =imread('alifMad54.bmp');
alifMad55 =imread('alifMad55.bmp');
alifMad56 =imread('alifMad56.bmp');
alifMad57 =imread('alifMad57.bmp');
alifMad58 =imread('alifMad58.bmp');
alifMad59 =imread('alifMad59.bmp');
alifMad60 =imread('alifMad60.bmp');
alifMad61 =imread('alifMad61.bmp');
alifMad62=imread('alifMad62.bmp');
alifMad63 =imread('alifMad63.bmp');
alifMad64 =imread('alifMad64.bmp');
alifMad65 =imread('alifMad65.bmp');
alifMad66 =imread('alifMad66.bmp');
alifMad67 =imread('alifMad67.bmp');
alifMad68 =imread('alifMad68.bmp');
alifMad69 =imread('alifMad69.bmp');
alifMad70 =imread('alifMad70.bmp');
alifMad71 =imread('alifMad71.bmp');
alifMad72=imread('alifMad72.bmp');
alifMad73 =imread('alifMad73.bmp');
alifMad74 =imread('alifMad74.bmp');
alifMad75 =imread('alifMad75.bmp');
alifMad76 =imread('alifMad76.bmp');
alifMad77 =imread('alifMad77.bmp');
alifMad78 =imread('alifMad78.bmp');
alifMad79 =imread('alifMad79.bmp');
alifMad80 =imread('alifMad80.bmp');
alifMad81 =imread('alifMad81.bmp');
alifMad82=imread('alifMad82.bmp');
alifMad83 =imread('alifMad83.bmp');
alifMad84 =imread('alifMad84.bmp');
alifMad85 =imread('alifMad85.bmp');
alifMad86 =imread('alifMad86.bmp');
alifMad87 =imread('alifMad87.bmp');
alifMad88 =imread('alifMad88.bmp');
alifMad89 =imread('alifMad89.bmp');
alifMad90 =imread('alifMad90.bmp');
alifMad91 =imread('alifMad91.bmp');
alifMad92=imread('alifMad92.bmp');
alifMad93 =imread('alifMad93.bmp');
alifMad94 =imread('alifMad94.bmp');
alifMad95 =imread('alifMad95.bmp');
alifMad96 =imread('alifMad96.bmp');
alifMad97 =imread('alifMad97.bmp');
alifMad98 =imread('alifMad98.bmp');
alifMad99 =imread('alifMad99.bmp');
alifMad100 =imread('alifMad100.bmp');


level = graythresh(alifMad1);         alifMadBW1 = im2bw(alifMad1,level);
level = graythresh(alifMad2);         alifMadBW2 = im2bw(alifMad2,level);
level = graythresh(alifMad3);         alifMadBW3 = im2bw(alifMad3,level);
level = graythresh(alifMad4);         alifMadBW4 = im2bw(alifMad4,level);
level = graythresh(alifMad5);         alifMadBW5 = im2bw(alifMad5,level);
level = graythresh(alifMad6);         alifMadBW6 = im2bw(alifMad6,level);
level = graythresh(alifMad7);         alifMadBW7 = im2bw(alifMad7,level);
level = graythresh(alifMad8);         alifMadBW8 = im2bw(alifMad8,level);
level = graythresh(alifMad9);         alifMadBW9 = im2bw(alifMad9,level);
level = graythresh(alifMad10);        alifMadBW10 = im2bw(alifMad10,level);
level = graythresh(alifMad11);         alifMadBW11 = im2bw(alifMad11,level);
level = graythresh(alifMad12);         alifMadBW12 = im2bw(alifMad12,level);
level = graythresh(alifMad13);         alifMadBW13 = im2bw(alifMad13,level);
level = graythresh(alifMad14);         alifMadBW14 = im2bw(alifMad14,level);
level = graythresh(alifMad15);         alifMadBW15 = im2bw(alifMad15,level);
level = graythresh(alifMad16);         alifMadBW16 = im2bw(alifMad16,level);
level = graythresh(alifMad17);         alifMadBW17 = im2bw(alifMad17,level);
level = graythresh(alifMad18);         alifMadBW18 = im2bw(alifMad18,level);
level = graythresh(alifMad19);         alifMadBW19 = im2bw(alifMad19,level);
level = graythresh(alifMad20);        alifMadBW20 = im2bw(alifMad20,level);
level = graythresh(alifMad21);         alifMadBW21 = im2bw(alifMad21,level);
level = graythresh(alifMad22);         alifMadBW22 = im2bw(alifMad22,level);
level = graythresh(alifMad23);         alifMadBW23 = im2bw(alifMad23,level);
level = graythresh(alifMad24);         alifMadBW24 = im2bw(alifMad24,level);
level = graythresh(alifMad25);         alifMadBW25 = im2bw(alifMad25,level);
level = graythresh(alifMad26);         alifMadBW26 = im2bw(alifMad26,level);
level = graythresh(alifMad27);         alifMadBW27 = im2bw(alifMad27,level);
level = graythresh(alifMad28);         alifMadBW28 = im2bw(alifMad28,level);
level = graythresh(alifMad29);         alifMadBW29 = im2bw(alifMad29,level);
level = graythresh(alifMad30);        alifMadBW30 = im2bw(alifMad30,level);
level = graythresh(alifMad31);         alifMadBW31 = im2bw(alifMad31,level);
level = graythresh(alifMad32);         alifMadBW32 = im2bw(alifMad32,level);
level = graythresh(alifMad33);         alifMadBW33 = im2bw(alifMad33,level);
level = graythresh(alifMad34);         alifMadBW34 = im2bw(alifMad34,level);
level = graythresh(alifMad35);         alifMadBW35 = im2bw(alifMad35,level);
level = graythresh(alifMad36);         alifMadBW36 = im2bw(alifMad36,level);
level = graythresh(alifMad37);         alifMadBW37 = im2bw(alifMad37,level);
level = graythresh(alifMad38);         alifMadBW38 = im2bw(alifMad38,level);
level = graythresh(alifMad39);         alifMadBW39 = im2bw(alifMad39,level);
level = graythresh(alifMad40);        alifMadBW40 = im2bw(alifMad40,level);
level = graythresh(alifMad41);         alifMadBW41 = im2bw(alifMad41,level);
level = graythresh(alifMad42);         alifMadBW42 = im2bw(alifMad42,level);
level = graythresh(alifMad43);         alifMadBW43 = im2bw(alifMad43,level);
level = graythresh(alifMad44);         alifMadBW44 = im2bw(alifMad44,level);
level = graythresh(alifMad45);         alifMadBW45 = im2bw(alifMad45,level);
level = graythresh(alifMad46);         alifMadBW46 = im2bw(alifMad46,level);
level = graythresh(alifMad47);         alifMadBW47 = im2bw(alifMad47,level);
level = graythresh(alifMad48);         alifMadBW48 = im2bw(alifMad48,level);
level = graythresh(alifMad49);         alifMadBW49 = im2bw(alifMad49,level);
level = graythresh(alifMad50);        alifMadBW50 = im2bw(alifMad50,level);
level = graythresh(alifMad51);         alifMadBW51 = im2bw(alifMad51,level);
level = graythresh(alifMad52);         alifMadBW52 = im2bw(alifMad52,level);
level = graythresh(alifMad53);         alifMadBW53 = im2bw(alifMad53,level);
level = graythresh(alifMad54);         alifMadBW54 = im2bw(alifMad54,level);
level = graythresh(alifMad55);         alifMadBW55 = im2bw(alifMad55,level);
level = graythresh(alifMad56);         alifMadBW56 = im2bw(alifMad56,level);
level = graythresh(alifMad57);         alifMadBW57 = im2bw(alifMad57,level);
level = graythresh(alifMad58);         alifMadBW58 = im2bw(alifMad58,level);
level = graythresh(alifMad59);         alifMadBW59 = im2bw(alifMad59,level);
level = graythresh(alifMad60);        alifMadBW60 = im2bw(alifMad60,level);
level = graythresh(alifMad61);         alifMadBW61 = im2bw(alifMad61,level);
level = graythresh(alifMad62);         alifMadBW62 = im2bw(alifMad62,level);
level = graythresh(alifMad63);         alifMadBW63 = im2bw(alifMad63,level);
level = graythresh(alifMad64);         alifMadBW64 = im2bw(alifMad64,level);
level = graythresh(alifMad65);         alifMadBW65 = im2bw(alifMad65,level);
level = graythresh(alifMad66);         alifMadBW66 = im2bw(alifMad66,level);
level = graythresh(alifMad67);         alifMadBW67 = im2bw(alifMad67,level);
level = graythresh(alifMad68);         alifMadBW68 = im2bw(alifMad68,level);
level = graythresh(alifMad69);         alifMadBW69 = im2bw(alifMad69,level);
level = graythresh(alifMad70);        alifMadBW70 = im2bw(alifMad70,level);
level = graythresh(alifMad71);         alifMadBW71 = im2bw(alifMad71,level);
level = graythresh(alifMad72);         alifMadBW72 = im2bw(alifMad72,level);
level = graythresh(alifMad73);         alifMadBW73 = im2bw(alifMad73,level);
level = graythresh(alifMad74);         alifMadBW74 = im2bw(alifMad74,level);
level = graythresh(alifMad75);         alifMadBW75 = im2bw(alifMad75,level);
level = graythresh(alifMad76);         alifMadBW76 = im2bw(alifMad76,level);
level = graythresh(alifMad77);         alifMadBW77 = im2bw(alifMad77,level);
level = graythresh(alifMad78);         alifMadBW78 = im2bw(alifMad78,level);
level = graythresh(alifMad79);         alifMadBW79 = im2bw(alifMad79,level);
level = graythresh(alifMad80);        alifMadBW80 = im2bw(alifMad80,level);
level = graythresh(alifMad81);         alifMadBW81 = im2bw(alifMad81,level);
level = graythresh(alifMad82);         alifMadBW82 = im2bw(alifMad82,level);
level = graythresh(alifMad83);         alifMadBW83 = im2bw(alifMad83,level);
level = graythresh(alifMad84);         alifMadBW84 = im2bw(alifMad84,level);
level = graythresh(alifMad85);         alifMadBW85 = im2bw(alifMad85,level);
level = graythresh(alifMad86);         alifMadBW86 = im2bw(alifMad86,level);
level = graythresh(alifMad87);         alifMadBW87 = im2bw(alifMad87,level);
level = graythresh(alifMad88);         alifMadBW88 = im2bw(alifMad88,level);
level = graythresh(alifMad89);         alifMadBW89 = im2bw(alifMad89,level);
level = graythresh(alifMad90);        alifMadBW90 = im2bw(alifMad90,level);
level = graythresh(alifMad91);         alifMadBW91 = im2bw(alifMad91,level);
level = graythresh(alifMad92);         alifMadBW92 = im2bw(alifMad92,level);
level = graythresh(alifMad93);         alifMadBW93 = im2bw(alifMad93,level);
level = graythresh(alifMad94);         alifMadBW94 = im2bw(alifMad94,level);
level = graythresh(alifMad95);         alifMadBW95 = im2bw(alifMad95,level);
level = graythresh(alifMad96);         alifMadBW96 = im2bw(alifMad96,level);
level = graythresh(alifMad97);         alifMadBW97 = im2bw(alifMad97,level);
level = graythresh(alifMad98);         alifMadBW98 = im2bw(alifMad98,level);
level = graythresh(alifMad99);         alifMadBW99 = im2bw(alifMad99,level);
level = graythresh(alifMad100);        alifMadBW100 = im2bw(alifMad100,level);


alifMadL1=double(array2vector(rw,cl,alifMadBW1));
alifMadL2=double(array2vector(rw,cl,alifMadBW2));
alifMadL3=double(array2vector(rw,cl,alifMadBW3));
alifMadL4=double(array2vector(rw,cl,alifMadBW4));
alifMadL5=double(array2vector(rw,cl,alifMadBW5));
alifMadL6=double(array2vector(rw,cl,alifMadBW6));
alifMadL7=double(array2vector(rw,cl,alifMadBW7));
alifMadL8=double(array2vector(rw,cl,alifMadBW8));
alifMadL9=double(array2vector(rw,cl,alifMadBW9));
alifMadL10=double(array2vector(rw,cl,alifMadBW10));
alifMadL11=double(array2vector(rw,cl,alifMadBW11));
alifMadL12=double(array2vector(rw,cl,alifMadBW12));
alifMadL13=double(array2vector(rw,cl,alifMadBW13));
alifMadL14=double(array2vector(rw,cl,alifMadBW14));
alifMadL15=double(array2vector(rw,cl,alifMadBW15));
alifMadL16=double(array2vector(rw,cl,alifMadBW16));
alifMadL17=double(array2vector(rw,cl,alifMadBW17));
alifMadL18=double(array2vector(rw,cl,alifMadBW18));
alifMadL19=double(array2vector(rw,cl,alifMadBW19));
alifMadL20=double(array2vector(rw,cl,alifMadBW20));
alifMadL21=double(array2vector(rw,cl,alifMadBW21));
alifMadL22=double(array2vector(rw,cl,alifMadBW22));
alifMadL23=double(array2vector(rw,cl,alifMadBW23));
alifMadL24=double(array2vector(rw,cl,alifMadBW24));
alifMadL25=double(array2vector(rw,cl,alifMadBW25));
alifMadL26=double(array2vector(rw,cl,alifMadBW26));
alifMadL27=double(array2vector(rw,cl,alifMadBW27));
alifMadL28=double(array2vector(rw,cl,alifMadBW28));
alifMadL29=double(array2vector(rw,cl,alifMadBW29));
alifMadL30=double(array2vector(rw,cl,alifMadBW30));
alifMadL31=double(array2vector(rw,cl,alifMadBW31));
alifMadL32=double(array2vector(rw,cl,alifMadBW32));
alifMadL33=double(array2vector(rw,cl,alifMadBW33));
alifMadL34=double(array2vector(rw,cl,alifMadBW34));
alifMadL35=double(array2vector(rw,cl,alifMadBW35));
alifMadL36=double(array2vector(rw,cl,alifMadBW36));
alifMadL37=double(array2vector(rw,cl,alifMadBW37));
alifMadL38=double(array2vector(rw,cl,alifMadBW38));
alifMadL39=double(array2vector(rw,cl,alifMadBW39));
alifMadL40=double(array2vector(rw,cl,alifMadBW40));
alifMadL41=double(array2vector(rw,cl,alifMadBW41));
alifMadL42=double(array2vector(rw,cl,alifMadBW42));
alifMadL43=double(array2vector(rw,cl,alifMadBW43));
alifMadL44=double(array2vector(rw,cl,alifMadBW44));
alifMadL45=double(array2vector(rw,cl,alifMadBW45));
alifMadL46=double(array2vector(rw,cl,alifMadBW46));
alifMadL47=double(array2vector(rw,cl,alifMadBW47));
alifMadL48=double(array2vector(rw,cl,alifMadBW48));
alifMadL49=double(array2vector(rw,cl,alifMadBW49));
alifMadL50=double(array2vector(rw,cl,alifMadBW50));
alifMadL51=double(array2vector(rw,cl,alifMadBW51));
alifMadL52=double(array2vector(rw,cl,alifMadBW52));
alifMadL53=double(array2vector(rw,cl,alifMadBW53));
alifMadL54=double(array2vector(rw,cl,alifMadBW54));
alifMadL55=double(array2vector(rw,cl,alifMadBW55));
alifMadL56=double(array2vector(rw,cl,alifMadBW56));
alifMadL57=double(array2vector(rw,cl,alifMadBW57));
alifMadL58=double(array2vector(rw,cl,alifMadBW58));
alifMadL59=double(array2vector(rw,cl,alifMadBW59));
alifMadL60=double(array2vector(rw,cl,alifMadBW60));
alifMadL61=double(array2vector(rw,cl,alifMadBW1));
alifMadL62=double(array2vector(rw,cl,alifMadBW62));
alifMadL63=double(array2vector(rw,cl,alifMadBW63));
alifMadL64=double(array2vector(rw,cl,alifMadBW64));
alifMadL65=double(array2vector(rw,cl,alifMadBW65));
alifMadL66=double(array2vector(rw,cl,alifMadBW66));
alifMadL67=double(array2vector(rw,cl,alifMadBW67));
alifMadL68=double(array2vector(rw,cl,alifMadBW68));
alifMadL69=double(array2vector(rw,cl,alifMadBW69));
alifMadL70=double(array2vector(rw,cl,alifMadBW70));
alifMadL71=double(array2vector(rw,cl,alifMadBW71));
alifMadL72=double(array2vector(rw,cl,alifMadBW72));
alifMadL73=double(array2vector(rw,cl,alifMadBW73));
alifMadL74=double(array2vector(rw,cl,alifMadBW74));
alifMadL75=double(array2vector(rw,cl,alifMadBW75));
alifMadL76=double(array2vector(rw,cl,alifMadBW76));
alifMadL77=double(array2vector(rw,cl,alifMadBW77));
alifMadL78=double(array2vector(rw,cl,alifMadBW78));
alifMadL79=double(array2vector(rw,cl,alifMadBW79));
alifMadL80=double(array2vector(rw,cl,alifMadBW80));
alifMadL81=double(array2vector(rw,cl,alifMadBW81));
alifMadL82=double(array2vector(rw,cl,alifMadBW82));
alifMadL83=double(array2vector(rw,cl,alifMadBW83));
alifMadL84=double(array2vector(rw,cl,alifMadBW84));
alifMadL85=double(array2vector(rw,cl,alifMadBW85));
alifMadL86=double(array2vector(rw,cl,alifMadBW86));
alifMadL87=double(array2vector(rw,cl,alifMadBW87));
alifMadL88=double(array2vector(rw,cl,alifMadBW88));
alifMadL89=double(array2vector(rw,cl,alifMadBW89));
alifMadL90=double(array2vector(rw,cl,alifMadBW90));
alifMadL91=double(array2vector(rw,cl,alifMadBW91));
alifMadL92=double(array2vector(rw,cl,alifMadBW92));
alifMadL93=double(array2vector(rw,cl,alifMadBW93));
alifMadL94=double(array2vector(rw,cl,alifMadBW94));
alifMadL95=double(array2vector(rw,cl,alifMadBW95));
alifMadL96=double(array2vector(rw,cl,alifMadBW96));
alifMadL97=double(array2vector(rw,cl,alifMadBW97));
alifMadL98=double(array2vector(rw,cl,alifMadBW98));
alifMadL99=double(array2vector(rw,cl,alifMadBW99));
alifMadL100=double(array2vector(rw,cl,alifMadBW100));


alifMad=[alifMadL1,alifMadL2,alifMadL3,alifMadL4,alifMadL5,alifMadL6,alifMadL7,alifMadL8,alifMadL9,alifMadL10,...
      alifMadL11,alifMadL12,alifMadL13,alifMadL14,alifMadL15,alifMadL16,alifMadL17,alifMadL18,alifMadL19,alifMadL20,...
      alifMadL21,alifMadL22,alifMadL23,alifMadL24,alifMadL25,alifMadL26,alifMadL27,alifMadL28,alifMadL29,alifMadL30,...
      alifMadL31,alifMadL32,alifMadL33,alifMadL34,alifMadL35,alifMadL36,alifMadL37,alifMadL38,alifMadL39,alifMadL40,...
      alifMadL41,alifMadL42,alifMadL43,alifMadL44,alifMadL45,alifMadL46,alifMadL47,alifMadL48,alifMadL49,alifMadL50,...
      alifMadL51,alifMadL52,alifMadL53,alifMadL54,alifMadL55,alifMadL56,alifMadL57,alifMadL58,alifMadL59,alifMadL60,...
      alifMadL61,alifMadL62,alifMadL63,alifMadL64,alifMadL65,alifMadL66,alifMadL67,alifMadL68,alifMadL69,alifMadL70,...
      alifMadL71,alifMadL72,alifMadL73,alifMadL74,alifMadL75,alifMadL76,alifMadL77,alifMadL78,alifMadL79,alifMadL80,...
      alifMadL81,alifMadL82,alifMadL83,alifMadL84,alifMadL85,alifMadL86,alifMadL87,alifMadL88,alifMadL89,alifMadL90,...
      alifMadL91,alifMadL92,alifMadL93,alifMadL94,alifMadL95,alifMadL96,alifMadL97,alifMadL98,alifMadL99,alifMadL100];


